services:
  - type: web
    name: todo-notification-service
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: HASURA_ENDPOINT
        sync: false
      - key: HASURA_ADMIN_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
